name: CD Back-end

on: 
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  
jobs:

  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend-main.yml
    
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Railsway
    steps: 
      - uses: actions/checkout@v3
      - name: Set up node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalção do cliente Angular
        run: npm install -g @angular/cli
      - name: Instalação do cliente Railway
        run: npm install -g @railway/cli
      - name: Deploy
        working-directory: front-end/dist/sgcmapp
        run: railway up --detach --service sgcm-hermann-frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
    
    
    
    
