name: CI Back-end

on: 
  push:
    branches:
      - 'main'
    paths:
      - 'back-end/**'
  
jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - name: Test
        working-directory: back-end/
        run: mvn --activate-profiles prod test
  package:
    runs-on: ubuntu-lastest
    steps:
      - name: Package
        working-directory: back-end/
        run: mvn --activate-profiles prod -DskipTests package
