name: CI Back-end

on: 
  push:
    branches:
      - 'main'
    paths:
      - 'back-end/**'
  
jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilation, Test
        working-directory: back-end/
        run: mvn --activate-profiles prod test
  package:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilation, Package
        working-directory: back-end/
        run: mvn --activate-profiles prod -DskipTests package

